# Generated by Django 5.2.8 on 2025-12-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
